# Generated by Django 3.2 on 2021-05-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='desc',
            field=models.TextField(blank=True, help_text='Client description', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, help_text='Project description', null=True),
        ),
    ]
