# Generated by Django 3.2 on 2021-07-17 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_auto_20210517_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='general.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='megeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
