# Generated by Django 3.2 on 2021-07-17 21:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


def create_currency(apps, schema_editor):
    corrency_manager = apps.get_model('general.currency').objects
    corrency_manager.create(
        id=1,
        name='USD',
        desc='Dolar Estadounidense',
        synbol='$',
        
    )

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_megeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency name', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='Currency description', null=True)),
                ('synbol', models.CharField(help_text='Currency synbol', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_currency),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='Customer description', null=True)),
                ('addess', models.TextField(blank=True, help_text='Customer address', null=True, verbose_name='Address')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=' ', max_length=128, null=True), blank=True, default=list, help_text='Customer phones', null=True, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, default=' ', max_length=128, null=True), blank=True, default=list, help_text='Customer EMails', null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curtomers', to='general.client')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Local name', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='Local description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='remove_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='UnitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='UnitCost name', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='UnitCost description', null=True)),
                ('unit', models.CharField(help_text='Unit', max_length=128)),
                ('value', models.FloatField(help_text='Unit cost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_costs', to='general.client')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='general.customer')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='general.local')),
            ],
        ),
        migrations.AddField(
            model_name='local',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local', to='general.project'),
        ),
        migrations.AddField(
            model_name='client',
            name='currency_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='general.currency', verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='currency_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='general.currency', verbose_name='currency'),
        ),
    ]
