# Generated by Django 3.2 on 2021-07-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20210717_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='remove_at',
            new_name='removed_at',
        ),
    ]
