# Generated by Django 3.2 on 2021-07-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20210725_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='currency_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='general.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtomers', to='general.client'),
        ),
        migrations.AlterField(
            model_name='local',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='general.project'),
        ),
        migrations.AlterField(
            model_name='megeuser',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='general.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='general.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='general.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='unitcost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_costs', to='general.client'),
        ),
    ]
