# Generated by Django 3.2.6 on 2021-08-18 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210725_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_id_generator',
            field=models.CharField(choices=[('UUID', 'UUID Generator')], default='UUID', help_text='Invoice id generator', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_tax',
            field=models.FloatField(default=0.0, help_text='Tax % on invoice', validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_id_generator',
            field=models.CharField(blank=True, choices=[('UUID', 'UUID Generator')], help_text='Invoice id generator', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_tax',
            field=models.FloatField(blank=True, help_text='Tax % on invoice', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_id',
            field=models.CharField(blank=True, help_text='Legal identifier', max_length=128, null=True),
        ),
    ]
