# Generated by Django 3.2.6 on 2021-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20210817_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_invoice_header',
            field=models.BooleanField(default=False),
        ),
    ]
