# Generated by Django 3.2.13 on 2022-07-10 20:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_unitcost_invoice_item_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='invoice_maker',
            field=models.CharField(default='Plaza Real', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_maker_kwargs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_makers_allowed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PLAZA_REAL', 'Plaza Real')], max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_maker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_maker_kwargs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
