# Generated by Django 3.2.13 on 2022-07-24 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20220710_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='invoice_makers_allowed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(None, '-----'), ('PLAZA_REAL', 'Plaza Real'), ('BUSINESS_PARK', 'Business Park')], max_length=20), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invoice_id_generator_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invoice_maker_kwargs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
