# Generated by Django 3.2 on 2021-05-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0002_auto_20210517_2137'),
        ('data_export', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportDataProxyModel',
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
            ],
            options={
                'verbose_name': 'Data export',
                'verbose_name_plural': 'Data export',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('x6gateapi.rtdata',),
        ),
    ]
