# Generated by Django 3.2 on 2021-04-11 16:18

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=128)),
                ('id', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('ver', models.CharField(blank=True, max_length=128, null=True)),
                ('site', models.JSONField()),
                ('owner', models.JSONField()),
                ('room', models.JSONField()),
                ('time_zone', timezone_field.fields.TimeZoneField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateways', to='general.project')),
            ],
            options={
                'unique_together': {('project', 'sn')},
            },
        ),
        migrations.CreateModel(
            name='RTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdt', models.CharField(blank=True, max_length=128, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('discard', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='x6gateapi.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='RTAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdt', models.CharField(blank=True, max_length=128, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('threadhold_value', models.CharField(blank=True, max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('flag', models.CharField(blank=True, max_length=128, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='x6gateapi.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='x6gateapi.gateway'),
        ),
        migrations.CreateModel(
            name='DataNone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dblink', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('discard', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='x6gateapi.rtdata')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='x6gateapi.device')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('gateway', 'channel', 'id')},
        ),
        migrations.AddIndex(
            model_name='datanone',
            index=models.Index(fields=['device', 'data', 'name'], name='x6gateapi_d_device__307bf6_idx'),
        ),
    ]
