# Generated by Django 3.2 on 2021-07-18 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_rename_remove_at_project_removed_at'),
        ('x6gateapi', '0002_auto_20210517_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanone',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rtalarm',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rtdata',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trendlogdata',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Measure name', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='Measure description', null=True)),
                ('var_name', models.CharField(help_text='Device variable name', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='x6gateapi.device')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='general.local')),
                ('unit_cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measures', to='general.unitcost'))
            ],
        ),
    ]
