# Generated by Django 3.2 on 2021-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0003_auto_20210718_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='data_source',
            field=models.CharField(choices=[('RT', 'Real time data'), ('TL', 'Trend log data')], default='RT', max_length=5),
        ),
    ]
