# Generated by Django 3.2 on 2021-07-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20210725_0905'),
        ('x6gateapi', '0005_alter_measure_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='x6gateapi.device'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='general.local'),
        ),
    ]
