# Generated by Django 3.2.6 on 2021-08-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0006_auto_20210725_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='calculator',
            field=models.CharField(choices=[('TEST', 'TEST calculator')], default='TEST', help_text='Measuer calculator', max_length=20),
        ),
        migrations.AddField(
            model_name='measure',
            name='calculator_args',
            field=models.JSONField(default=list, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='calculator_kwargs',
            field=models.JSONField(default=dict, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='x6gateapi.device'),
        ),
    ]
