# Generated by Django 3.2.6 on 2021-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0007_auto_20210817_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='calculator',
            field=models.CharField(choices=[('PLZR_CONSUMO_AA', 'Consumo de AA')], default='TEST', help_text='Measuer calculator', max_length=20),
        ),
    ]
