# Generated by Django 3.2.6 on 2021-08-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0008_alter_measure_calculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='device',
        ),
    ]
