# Generated by Django 3.2.6 on 2021-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0009_auto_20210822_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='secret_extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
