# Generated by Django 3.2.6 on 2021-11-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0010_auto_20211107_1426'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rtdata',
            unique_together={('gateway', 'date_time')},
        ),
    ]
