# Generated by Django 3.2.6 on 2021-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0011_alter_rtdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='calculator',
            field=models.CharField(choices=[('PLZR_CONSUMO_AA', 'Consumo de AA'), ('PLZR_OCCUPATION_AA', 'Ocupación de AA')], default='TEST', help_text='Measuer calculator', max_length=20),
        ),
    ]
