# Generated by Django 3.2.6 on 2021-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0012_alter_measure_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='calculator',
            field=models.CharField(choices=[('PLZR_CONSUMO_AA', 'Consumo de AA'), ('PLZR_OCCUPATION_AA', 'Ocupación de AA'), ('PLZR_CONSUMOTD_AA', 'Consumo de Total diario AA')], default='TEST', help_text='Measuer calculator', max_length=20),
        ),
    ]
