# Generated by Django 3.2.6 on 2022-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0013_alter_measure_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='calculator',
            field=models.CharField(choices=[('PLZR_CONSUMO_AA', 'Consumo de AA'), ('PLZR_OCCUPATION_AA', 'Ocupación de AA'), ('PLZR_CONSUMOTD_AA', 'Consumo de Total diario AA'), ('BUSSPARK_CONSUMO_W', 'Consumo de Kwh')], default='TEST', help_text='Measuer calculator', max_length=20),
        ),
        migrations.AlterField(
            model_name='measure',
            name='var_name',
            field=models.CharField(help_text='Device variable name', max_length=128, null=True),
        ),
    ]
