# Generated by Django 3.2.6 on 2022-05-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0014_auto_20220526_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='var_name',
            field=models.CharField(blank=True, help_text='Device variable name', max_length=128, null=True),
        ),
    ]
