# Generated by Django 3.2.13 on 2022-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0015_alter_measure_var_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtalarm',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rtalarm',
            name='value',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='rtalarm',
            index=models.Index(fields=['device', 'logdt'], name='x6gateapi_r_device__f88d8e_idx'),
        ),
    ]
