# Generated by Django 3.2.13 on 2022-07-03 21:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0016_auto_20220703_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('device_channel', models.CharField(max_length=128)),
                ('device_id', models.CharField(max_length=10)),
                ('subject_template', models.TextField(null=True)),
                ('msg_template', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='x6gateapi.gateway')),
            ],
        ),
    ]
