# Generated by Django 3.2.13 on 2022-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0017_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='from_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='from_email_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
