# Generated by Django 3.2.13 on 2022-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0018_auto_20220703_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='name',
            field=models.CharField(default='Alerta', max_length=128),
        ),
    ]
