# Generated by Django 3.2.13 on 2022-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0019_alert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
