# Generated by Django 3.2.13 on 2022-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0020_alter_alert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='from_email_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
