# Generated by Django 3.2.13 on 2022-07-19 00:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0021_auto_20220705_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='html_msg_template',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
