# Generated by Django 3.2.13 on 2022-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0022_alert_html_msg_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtalarm',
            name='value',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
