# Generated by Django 3.2.13 on 2022-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x6gateapi', '0023_alter_rtalarm_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
